<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_rootstack [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (rootstack)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT rootstack (treeline, connector)>
	<!ATTLIST rootstack id NMTOKEN #REQUIRED>
	<!ATTLIST rootstack expanded NMTOKEN #REQUIRED>
	<!ELEMENT treeline EMPTY>
	<!ATTLIST treeline id NMTOKEN #REQUIRED>
	<!ATTLIST treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST treeline expanded NMTOKEN #REQUIRED>
	<!ELEMENT connector EMPTY>
	<!ATTLIST connector id NMTOKEN #REQUIRED>
	<!ATTLIST connector oid NMTOKEN #REQUIRED>
	<!ATTLIST connector expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="rhizoTrak_t23.xml"
		unuid="1535470072952.1769088566.105536570"
		mipmaps_folder="trakem2.1535470072952.1769088566.105536570/trakem2.mipmaps/"
		storage_folder=""
		mipmaps_format="4"
		image_resizing_mode="Area downsampling"
		first_mipmap_level_saved="0"
	>
		<rootstack id="9" expanded="true">
			<treeline id="25" oid="24"/>
			<treeline id="27" oid="26"/>
			<treeline id="30" oid="29"/>
			<treeline id="32" oid="31"/>
			<treeline id="34" oid="33"/>
			<treeline id="36" oid="35"/>
			<treeline id="38" oid="37"/>
			<treeline id="40" oid="39"/>
			<treeline id="42" oid="41"/>
			<treeline id="44" oid="43"/>
			<treeline id="46" oid="45"/>
			<treeline id="48" oid="47"/>
			<treeline id="50" oid="49"/>
			<treeline id="52" oid="51"/>
			<treeline id="54" oid="53"/>
			<treeline id="56" oid="55"/>
			<treeline id="58" oid="57"/>
			<treeline id="60" oid="59"/>
			<treeline id="62" oid="61"/>
			<treeline id="64" oid="63"/>
			<treeline id="66" oid="65"/>
			<treeline id="68" oid="67"/>
			<treeline id="70" oid="69"/>
			<treeline id="72" oid="71"/>
			<treeline id="74" oid="73"/>
			<treeline id="76" oid="75"/>
			<treeline id="78" oid="77"/>
			<treeline id="80" oid="79"/>
			<treeline id="82" oid="81"/>
			<treeline id="84" oid="83"/>
			<treeline id="86" oid="85"/>
			<treeline id="88" oid="87"/>
			<treeline id="90" oid="89"/>
			<treeline id="92" oid="91"/>
			<treeline id="94" oid="93"/>
			<treeline id="96" oid="95"/>
			<treeline id="98" oid="97"/>
			<treeline id="100" oid="99"/>
			<treeline id="102" oid="101"/>
			<treeline id="104" oid="103"/>
			<treeline id="106" oid="105"/>
			<treeline id="108" oid="107"/>
			<treeline id="110" oid="109"/>
			<treeline id="112" oid="111"/>
			<treeline id="114" oid="113"/>
			<treeline id="116" oid="115"/>
			<treeline id="118" oid="117"/>
			<treeline id="120" oid="119"/>
			<treeline id="122" oid="121"/>
			<treeline id="124" oid="123"/>
			<treeline id="126" oid="125"/>
			<treeline id="128" oid="127"/>
			<treeline id="130" oid="129"/>
			<treeline id="132" oid="131"/>
			<treeline id="134" oid="133"/>
			<treeline id="136" oid="135"/>
			<treeline id="138" oid="137"/>
			<treeline id="140" oid="139"/>
			<treeline id="142" oid="141"/>
			<treeline id="144" oid="143"/>
			<treeline id="146" oid="145"/>
			<treeline id="148" oid="147"/>
			<treeline id="150" oid="149"/>
			<treeline id="152" oid="151"/>
			<treeline id="154" oid="153"/>
			<treeline id="156" oid="155"/>
			<treeline id="158" oid="157"/>
			<treeline id="160" oid="159"/>
			<treeline id="162" oid="161"/>
			<treeline id="164" oid="163"/>
			<treeline id="166" oid="165"/>
			<treeline id="168" oid="167"/>
			<treeline id="170" oid="169"/>
			<treeline id="172" oid="171"/>
			<treeline id="174" oid="173"/>
			<treeline id="176" oid="175"/>
			<treeline id="179" oid="178"/>
			<connector id="181" oid="180"/>
			<treeline id="183" oid="182"/>
			<connector id="185" oid="184"/>
			<treeline id="187" oid="186"/>
			<connector id="189" oid="188"/>
			<treeline id="191" oid="190"/>
			<connector id="193" oid="192"/>
			<treeline id="195" oid="194"/>
			<connector id="197" oid="196"/>
			<treeline id="199" oid="198"/>
			<connector id="201" oid="200"/>
			<treeline id="203" oid="202"/>
			<connector id="205" oid="204"/>
			<treeline id="207" oid="206"/>
			<connector id="209" oid="208"/>
			<treeline id="211" oid="210"/>
			<connector id="213" oid="212"/>
			<treeline id="215" oid="214"/>
			<connector id="217" oid="216"/>
			<treeline id="219" oid="218"/>
			<connector id="221" oid="220"/>
			<treeline id="223" oid="222"/>
			<connector id="225" oid="224"/>
			<treeline id="227" oid="226"/>
			<connector id="229" oid="228"/>
			<treeline id="231" oid="230"/>
			<connector id="233" oid="232"/>
			<treeline id="235" oid="234"/>
			<connector id="237" oid="236"/>
			<treeline id="239" oid="238"/>
			<connector id="241" oid="240"/>
			<treeline id="243" oid="242"/>
			<connector id="245" oid="244"/>
			<treeline id="247" oid="246"/>
			<connector id="249" oid="248"/>
			<treeline id="251" oid="250"/>
			<connector id="253" oid="252"/>
			<treeline id="255" oid="254"/>
			<connector id="257" oid="256"/>
			<treeline id="259" oid="258"/>
			<connector id="261" oid="260"/>
			<treeline id="263" oid="262"/>
			<connector id="265" oid="264"/>
			<treeline id="267" oid="266"/>
			<connector id="269" oid="268"/>
			<treeline id="271" oid="270"/>
			<connector id="273" oid="272"/>
			<treeline id="275" oid="274"/>
			<connector id="277" oid="276"/>
			<treeline id="279" oid="278"/>
			<connector id="281" oid="280"/>
			<treeline id="283" oid="282"/>
			<connector id="285" oid="284"/>
			<treeline id="287" oid="286"/>
			<connector id="289" oid="288"/>
			<treeline id="291" oid="290"/>
			<connector id="293" oid="292"/>
			<treeline id="295" oid="294"/>
			<connector id="297" oid="296"/>
			<treeline id="299" oid="298"/>
			<connector id="301" oid="300"/>
			<treeline id="303" oid="302"/>
			<connector id="305" oid="304"/>
			<treeline id="307" oid="306"/>
			<connector id="309" oid="308"/>
			<treeline id="311" oid="310"/>
			<connector id="313" oid="312"/>
			<treeline id="315" oid="314"/>
			<connector id="317" oid="316"/>
			<treeline id="319" oid="318"/>
			<connector id="321" oid="320"/>
			<treeline id="323" oid="322"/>
			<connector id="325" oid="324"/>
			<treeline id="327" oid="326"/>
			<connector id="329" oid="328"/>
			<treeline id="331" oid="330"/>
			<connector id="333" oid="332"/>
			<treeline id="335" oid="334"/>
			<connector id="337" oid="336"/>
			<treeline id="339" oid="338"/>
			<connector id="341" oid="340"/>
			<treeline id="343" oid="342"/>
			<connector id="345" oid="344"/>
			<treeline id="347" oid="346"/>
			<connector id="349" oid="348"/>
			<treeline id="351" oid="350"/>
			<connector id="353" oid="352"/>
			<treeline id="355" oid="354"/>
			<connector id="357" oid="356"/>
			<treeline id="359" oid="358"/>
			<connector id="361" oid="360"/>
			<treeline id="363" oid="362"/>
			<connector id="365" oid="364"/>
			<treeline id="367" oid="366"/>
			<connector id="369" oid="368"/>
			<treeline id="371" oid="370"/>
			<connector id="373" oid="372"/>
			<treeline id="375" oid="374"/>
			<connector id="377" oid="376"/>
			<treeline id="379" oid="378"/>
			<connector id="381" oid="380"/>
			<treeline id="383" oid="382"/>
			<connector id="385" oid="384"/>
			<treeline id="387" oid="386"/>
			<connector id="389" oid="388"/>
			<treeline id="391" oid="390"/>
			<connector id="393" oid="392"/>
			<treeline id="395" oid="394"/>
			<connector id="397" oid="396"/>
			<treeline id="399" oid="398"/>
			<connector id="401" oid="400"/>
			<treeline id="403" oid="402"/>
			<connector id="405" oid="404"/>
			<treeline id="407" oid="406"/>
			<connector id="409" oid="408"/>
			<treeline id="411" oid="410"/>
			<connector id="413" oid="412"/>
			<treeline id="415" oid="414"/>
			<connector id="417" oid="416"/>
			<treeline id="419" oid="418"/>
			<connector id="421" oid="420"/>
			<treeline id="423" oid="422"/>
			<connector id="425" oid="424"/>
			<treeline id="427" oid="426"/>
			<connector id="429" oid="428"/>
			<treeline id="431" oid="430"/>
			<connector id="433" oid="432"/>
			<treeline id="435" oid="434"/>
			<connector id="437" oid="436"/>
			<treeline id="439" oid="438"/>
			<connector id="441" oid="440"/>
			<treeline id="443" oid="442"/>
			<connector id="445" oid="444"/>
			<treeline id="447" oid="446"/>
			<connector id="449" oid="448"/>
			<treeline id="451" oid="450"/>
			<connector id="453" oid="452"/>
			<treeline id="455" oid="454"/>
			<connector id="457" oid="456"/>
			<treeline id="459" oid="458"/>
			<connector id="461" oid="460"/>
			<treeline id="463" oid="462"/>
			<connector id="465" oid="464"/>
			<treeline id="467" oid="466"/>
			<connector id="469" oid="468"/>
			<treeline id="471" oid="470"/>
			<connector id="473" oid="472"/>
			<treeline id="475" oid="474"/>
			<connector id="477" oid="476"/>
		</rootstack>
	</project>
	<t2_layer_set
		oid="5"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="2048.0"
		layer_height="2048.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="false"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_treeline
			oid="24"
			width="854.0"
			height="246.0"
			transform="matrix(1.0,0.0,0.0,1.0,0.0,49.0)"
			title="25"
			links=""
			layer_set_id="5"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;stroke-opacity:1.0"
		>
			<t2_node x="0.0" y="42.0" lid="7" color="00ff33" r="4.178211">
			<t2_node x="67.0" y="29.0" lid="7" c="0" color="00ff33" r="4.8486037">
			<t2_node x="160.0" y="19.0" lid="7" c="0" color="00ff33" r="3.9027953">
			<t2_node x="197.0" y="16.0" lid="7" c="0" color="00ff33" r="3.5078187">
			<t2_node x="232.0" y="5.0" lid="7" c="0" color="00ff33" r="4.0223556">
			<t2_node x="250.0" y="5.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="287.0" y="20.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="315.0" y="34.0" lid="7" c="0" color="00ff33" r="2.6815705">
			<t2_node x="331.0" y="48.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="350.0" y="60.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="375.0" y="71.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="412.0" y="85.0" lid="7" c="0" color="00ff33" r="2.6815705">
			<t2_node x="446.0" y="91.0" lid="7" c="0" color="00ff33" r="2.6815705">
			<t2_node x="506.0" y="96.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="561.0" y="109.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="578.0" y="116.0" lid="7" c="0" color="00ff33" r="4.0223556">
			<t2_node x="593.0" y="130.0" lid="7" c="0" color="00ff33" r="4.692748">
			<t2_node x="599.0" y="150.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="598.0" y="169.0" lid="7" c="0" color="00ff33" r="4.0223556">
			<t2_node x="607.0" y="185.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="629.0" y="210.0" lid="7" c="0" color="00ff33" r="4.0223556">
			<t2_node x="664.0" y="225.0" lid="7" c="0" color="00ff33" r="4.0223556">
			<t2_node x="708.0" y="238.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="739.0" y="243.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="783.0" y="240.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="854.0" y="229.0" lid="7" c="0" color="00ff33" r="3.351963" />
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
		</t2_treeline>
		<t2_treeline
			oid="26"
			width="1002.0"
			height="317.0"
			transform="matrix(1.0,0.0,0.0,1.0,-1.0,63.0)"
			title="27"
			links=""
			layer_set_id="5"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;stroke-opacity:1.0"
		>
			<t2_node x="1.0" y="45.0" lid="7" color="00ff33" r="4.692748">
			<t2_node x="56.0" y="30.0" lid="7" c="0" color="00ff33" r="4.0223556">
			<t2_node x="146.0" y="21.0" lid="7" c="0" color="00ff33" r="4.692748">
			<t2_node x="195.0" y="18.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="217.0" y="13.0" lid="7" c="0" color="00ff33" r="2.6815705">
			<t2_node x="238.0" y="5.0" lid="7" c="0" color="00ff33" r="4.692748">
			<t2_node x="261.0" y="11.0" lid="7" c="0" color="00ff33" r="4.692748">
			<t2_node x="288.0" y="41.0" lid="7" c="0" color="00ff33" r="6.7039256">
			<t2_node x="311.0" y="69.0" lid="7" c="0" color="00ff33" r="6.7039256">
			<t2_node x="326.0" y="95.0" lid="7" c="0" color="00ff33" r="6.7039256">
			<t2_node x="341.0" y="106.0" lid="7" c="0" color="00ff33" r="6.7039256">
			<t2_node x="405.0" y="141.0" lid="7" c="0" color="00ff33" r="6.7039256">
			<t2_node x="486.0" y="217.0" lid="7" c="0" color="00ff33" r="6.7039256">
			<t2_node x="533.0" y="234.0" lid="7" c="0" color="00ff33" r="6.033533">
			<t2_node x="577.0" y="247.0" lid="7" c="0" color="00ff33" r="6.033533">
			<t2_node x="633.0" y="252.0" lid="7" c="0" color="00ff33" r="6.033533">
			<t2_node x="678.0" y="262.0" lid="7" c="0" color="00ff33" r="6.033533">
			<t2_node x="717.0" y="263.0" lid="7" c="0" color="00ff33" r="6.033533">
			<t2_node x="802.0" y="284.0" lid="7" c="0" color="00ff33" r="6.033533">
			<t2_node x="913.0" y="298.0" lid="7" c="0" color="00ff33" r="6.033533">
			<t2_node x="943.0" y="312.0" lid="7" c="0" color="00ff33" r="5.3631406">
			<t2_node x="958.0" y="310.0" lid="7" c="0" color="00ff33" r="5.3631406">
			<t2_node x="978.0" y="293.0" lid="7" c="0" color="00ff33" r="6.7039256">
			<t2_node x="997.0" y="270.0" lid="7" c="0" color="00ff33" r="6.7039256" />
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
		</t2_treeline>
		<t2_treeline
			oid="29"
			width="116.0"
			height="22.0"
			transform="matrix(1.0,0.0,0.0,1.0,116.0,23.0)"
			title="30"
			links=""
			layer_set_id="5"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;stroke-opacity:1.0"
		>
			<t2_node x="0.0" y="9.0" lid="7" color="00ff33" r="3.351963">
			<t2_node x="25.0" y="4.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="56.0" y="4.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="88.0" y="12.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="116.0" y="19.0" lid="7" c="0" color="00ff33" r="3.351963" />
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
		</t2_treeline>
		<t2_treeline
			oid="31"
			width="243.0"
			height="201.0"
			transform="matrix(1.0,0.0,0.0,1.0,292.0,85.0)"
			title="32"
			links=""
			layer_set_id="5"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;stroke-opacity:1.0"
		>
			<t2_node x="2.0" y="2.0" lid="7" color="00ff33" r="2.6773005">
			<t2_node x="24.0" y="26.0" lid="7" c="0" color="00ff33" r="2.0026379">
			<t2_node x="38.0" y="51.0" lid="7" c="0" color="00ff33" r="2.0026379">
			<t2_node x="58.0" y="69.0" lid="7" c="0" color="00ff33" r="2.0026379">
			<t2_node x="83.0" y="81.0" lid="7" c="0" color="00ff33" r="2.0026379">
			<t2_node x="116.0" y="103.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="161.0" y="145.0" lid="7" c="0" color="00ff33" r="3.351963">
			<t2_node x="203.0" y="183.0" lid="7" c="0" color="00ff33" r="2.6773005">
			<t2_node x="212.0" y="188.0" lid="7" c="0" color="00ff33" r="2.6773005">
			<t2_node x="243.0" y="199.0" lid="7" c="0" color="00ff33" r="2.6773005" />
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
		</t2_treeline>
		<t2_treeline
			oid="33"
			width="96.0"
			height="79.0"
			transform="matrix(1.0,0.0,0.0,1.0,333.0,121.0)"
			title="34"
			links=""
			layer_set_id="5"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;stroke-opacity:1.0"
		>
			<t2_node x="2.0" y="0.0" lid="7" color="00ff33" r="2.6773005">
			<t2_node x="7.0" y="14.0" lid="7" c="0" color="00ff33" r="2.0026379">
			<t2_node x="20.0" y="26.0" lid="7" c="0" color="00ff33" r="2.0026379">
			<t2_node x="43.0" y="35.0" lid="7" c="0" color="00ff33" r="2.0026379">
			<t2_node x="62.0" y="44.0" lid="7" c="0" color="00ff33" r="2.0026379">
			<t2_node x="89.0" y="71.0" lid="7" c="0" color="00ff33" r="2.0026379">
			<t2_node x="95.0" y="78.0" lid="7" c="0" color="00ff33" r="2.0026379" />
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
			</t2_node>
		</t2_treeline>
		<t2_treeline
			oid="35"
			width="839.0"
			height="365.0"
			transform="matrix(1.0,0.0,0.0,1.0,340.0,47.0)"
			title="36"
			links=""
			layer_set_id="5"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;stroke-opacity:1.0"
		>
			<t2_node x="2.0" y="43.0" lid="7" color="00ff33" r="3.351963">
			<t2_node x="31.0" y="19.0" lid="7" c="0" color="00ff33" r="2.6773005">
			<t2_node x="60.0" y="5.0" lid="7" c="0" color="00ff33" r="2.6773005">
			<t2_node x="83.0" y="2.0" lid="7" c="0" color="00ff33" r="2.6773005">
			<t2_node x="113.0" y="9.0" lid="7" c="0" color="00ff33" r="2.6773005">